#!/bin/sh

EWW_DIR=$HOME/.config/eww/fool_moon
killall eww
NB_MONITORS=($(hyprctl monitors -j | jq -r '.[] | .id'))

for id in "${NB_MONITORS[@]}"; do
    # make top bar for every display
    bar="bar$id"
    hyprctl dispatch focusmonitor "$id"
    eww -c $EWW_DIR/bar open "$bar"
    eww -c $EWW_DIR/menu daemon
    # eww -c $EWW_DIR/menu open "sys-menu$id"
    eww -c $EWW_DIR/dashboard daemon
    eww -c $EWW_DIR/meters daemon
    echo $id
done
# eww -c $EWW_DIR/bar open bar
# eww -c $EWW_DIR/menu daemon
# eww -c $EWW_DIR/dashboard daemon
# eww -c $EWW_DIR/meters daemon

# $HOME/.config/eww/fool_moon/menu/scripts/sys restore

