#!/bin/bash

CACHE_DIR="$HOME/.cache/eww/"

function toggle() {
	if [ -f "$CACHE_DIR/dashboard.lock" ]; then
		rm "$CACHE_DIR/dashboard.lock"
		close
	else
		touch "$CACHE_DIR/dashboard.lock"
		open
	fi
}

function close() {
	eww -c "$HOME/.config/eww/fool_moon/dashboard" close darken clock power media
	eww -c "$HOME/.config/eww/fool_moon/meters" close meters
	eww -c "$HOME/.config/eww/fool_moon/bar" open bar
	for i in $(bspc query -N -n .window.hidden -d);do
		bspc node $i -g hidden=off
	done
	pkill glava
}

function open() {
	eww -c "$HOME/.config/eww/fool_moon/dashboard" open-many darken clock power media 
	eww -c "$HOME/.config/eww/fool_moon/meters" open meters
	eww -c "$HOME/.config/eww/fool_moon/bar" close bar
	for i in $(bspc query -N -n .window -d);do
		bspc node $i -g hidden=on
	done
	glava 1> /dev/null &
}

case "$1" in
	"open") open;;
	"close") close;;
	*) toggle;;
esac

