#!/bin/sh

hypr=$HOME/.config/hypr
wallpaper_folder=$HOME/Pictures/wallpapers

wallpaper_location="$(ls $wallpaper_folder | wofi -n --show dmenu)"

echo "$wallpaper_folder/$wallpaper_location"

if [[ -d $wallpaper_folder/$wallpaper_location ]]; then
    echo "$wallpaper_folder/$wallpaper_location is a directory"
    sleep2
    wallpaper_location="$(ls $wallpaper_folder/$wallpaper_location | wofi -n --show dmenu)"
elif [[ -f $wallpaper_folder/$wallpaper_location ]]; then
    echo "$wallpaper_folder/$wallpaper_location is a file"
else
    echo "$wallpaper_folder/$wallpaper_location is not valid"
    exit 1
fi

$hypr/scripts/variables/set_env background "$wallpaper_folder/$wallpaper_location"

$hypr/scripts/wallpaper
