#!/bin/sh

opacity_val=$(hyprctl getoption decoration:active_opacity | grep float)
echo "$opacity_val"
if [[ "$opacity_val" == "	float: 0.800000" ]]; then
    echo "float 0.8 detected"
    hyprctl --batch "keyword decoration:active_opacity 1.0 ; keyword decoration:inactive_opacity 1.0"
else
    echo "float 1.0 detected"
    hyprctl --batch "keyword decoration:active_opacity 0.8 ; keyword decoration:inactive_opacity 0.8"
fi


